// Code generated by go-skeleton.
// Code generated by go-skeleton.
// Code generated by go-skeleton.

package boots

import (
    "sync"
    {{range $item := .Dbs}}
    "{{$item.importPackage}}/internal/app/{{$item.dao}}"
    {{- end}}
    "{{.ImportPackage}}/internal/vars"
)

var once sync.Once

// InitDao ...
func InitDao() {
	once.Do(func() {
        {{- range $item := .Dbs}}
        // dao {{$item.alias}} set
        if vars.MDB["{{$item.alias}}"] != nil {
            {{$item.dao}}.SetDefault(vars.MDB["{{$item.alias}}"])
        }

        {{- end}}
	})
}
