// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameYfoAdmin = "yfo_admin"

// YfoAdmin 后台管理员表
type YfoAdmin struct {
	ID           int64  `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	UUID         string `gorm:"column:uuid;type:varchar(32);not null;comment:唯一id号" json:"uuid"`                           // 唯一id号
	Account      string `gorm:"column:account;type:varchar(64);not null;comment:账号" json:"account"`                        // 账号
	Password     string `gorm:"column:password;type:varchar(64);not null;comment:密码" json:"password"`                      // 密码
	Phone        string `gorm:"column:phone;type:varchar(16);not null;comment:手机号" json:"phone"`                           // 手机号
	Avatar       string `gorm:"column:avatar;type:varchar(128);not null;comment:头像" json:"avatar"`                         // 头像
	Salt         string `gorm:"column:salt;type:varchar(32);not null;comment:密码" json:"salt"`                              // 密码
	RealName     string `gorm:"column:real_name;type:varchar(64);not null;comment:真实姓名" json:"real_name"`                  // 真实姓名
	RegisterTime int64  `gorm:"column:register_time;type:bigint unsigned;not null;comment:注册时间" json:"register_time"`      // 注册时间
	RegisterIP   string `gorm:"column:register_ip;type:varchar(32);not null;comment:注册ip" json:"register_ip"`              // 注册ip
	LoginTime    int64  `gorm:"column:login_time;type:bigint unsigned;not null;comment:登录时间" json:"login_time"`            // 登录时间
	LoginIP      string `gorm:"column:login_ip;type:varchar(32);not null;comment:登录ip" json:"login_ip"`                    // 登录ip
	RoleIds      string `gorm:"column:role_ids;type:varchar(32);not null;comment:角色IDs" json:"role_ids"`                   // 角色IDs
	Status       int8   `gorm:"column:status;type:tinyint unsigned;not null;default:1;comment:状态 1：正常 2：禁用" json:"status"` // 状态 1：正常 2：禁用
	CreatedAt    int64  `gorm:"column:created_at;type:bigint unsigned;not null" json:"created_at"`
	UpdatedAt    int64  `gorm:"column:updated_at;type:bigint unsigned;not null" json:"updated_at"`
}

// TableName YfoAdmin's table name
func (*YfoAdmin) TableName() string {
	return TableNameYfoAdmin
}
